Search.appendIndex(
    [
                {
            "fqsen": "\\APP_ENV",
            "name": "APP_ENV",
            "summary": "",
            "url": "namespaces/default.html#constant_APP_ENV"
        },                {
            "fqsen": "\\ROOT_PATH",
            "name": "ROOT_PATH",
            "summary": "Framework\u0020root\u0020path.",
            "url": "namespaces/default.html#constant_ROOT_PATH"
        },                {
            "fqsen": "\\STORAGE_PATH",
            "name": "STORAGE_PATH",
            "summary": "Storage\u0020path.",
            "url": "namespaces/default.html#constant_STORAGE_PATH"
        },                {
            "fqsen": "\\MODULE_PATH",
            "name": "MODULE_PATH",
            "summary": "Modules\u0020path.",
            "url": "namespaces/default.html#constant_MODULE_PATH"
        },                {
            "fqsen": "\\PUBLIC_PATH",
            "name": "PUBLIC_PATH",
            "summary": "Public\u0020\u0028root\u0020web\u0029\u0020path.",
            "url": "namespaces/default.html#constant_PUBLIC_PATH"
        },                {
            "fqsen": "\\Rdb\\System\\App",
            "name": "App",
            "summary": "The\u0020framework\u0020kernel\u0020class.",
            "url": "classes/Rdb-System-App.html"
        },                {
            "fqsen": "\\Rdb\\System\\App\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Class\u0020constructor.",
            "url": "classes/Rdb-System-App.html#method___construct"
        },                {
            "fqsen": "\\Rdb\\System\\App\u003A\u003AaddDependencyInjection\u0028\u0029",
            "name": "addDependencyInjection",
            "summary": "Add\u0020dependency\u0020injection\u0020container\u0020to\u0020use\u0020between\u0020classes.",
            "url": "classes/Rdb-System-App.html#method_addDependencyInjection"
        },                {
            "fqsen": "\\Rdb\\System\\App\u003A\u003AcheckRequirements\u0028\u0029",
            "name": "checkRequirements",
            "summary": "Check\u0020requirements\u0020such\u0020as\u0020constants,\u0020PHP\u0020version.",
            "url": "classes/Rdb-System-App.html#method_checkRequirements"
        },                {
            "fqsen": "\\Rdb\\System\\App\u003A\u003AgetContainer\u0028\u0029",
            "name": "getContainer",
            "summary": "Get\u0020container\u0020object.",
            "url": "classes/Rdb-System-App.html#method_getContainer"
        },                {
            "fqsen": "\\Rdb\\System\\App\u003A\u003AgetMiddlewareConfig\u0028\u0029",
            "name": "getMiddlewareConfig",
            "summary": "Get\u0020middleware\u0020configuration\u0020from\u0020main\u0020app\u0020and\u0020modules.",
            "url": "classes/Rdb-System-App.html#method_getMiddlewareConfig"
        },                {
            "fqsen": "\\Rdb\\System\\App\u003A\u003AgetRouteErrorConfig\u0028\u0029",
            "name": "getRouteErrorConfig",
            "summary": "Get\u0020routes\u0020for\u0020error\u0020handler\u0020from\u0020main\u0020app\u0020and\u0020maybe\u0020replaced\u0020by\u0020other\u0020modules.",
            "url": "classes/Rdb-System-App.html#method_getRouteErrorConfig"
        },                {
            "fqsen": "\\Rdb\\System\\App\u003A\u003AloadAfterMiddleware\u0028\u0029",
            "name": "loadAfterMiddleware",
            "summary": "Load\u0020\u005Bafter\u005D\u0020middleware\u0020from\u0020config\u0020to\u0020run\u0020after\u0020the\u0020application\u0020started.",
            "url": "classes/Rdb-System-App.html#method_loadAfterMiddleware"
        },                {
            "fqsen": "\\Rdb\\System\\App\u003A\u003AloadBeforeMiddleware\u0028\u0029",
            "name": "loadBeforeMiddleware",
            "summary": "Load\u0020\u005Bbefore\u005D\u0020middleware\u0020from\u0020config\u0020to\u0020run\u0020before\u0020the\u0020application\u0020start.",
            "url": "classes/Rdb-System-App.html#method_loadBeforeMiddleware"
        },                {
            "fqsen": "\\Rdb\\System\\App\u003A\u003AprocessController\u0028\u0029",
            "name": "processController",
            "summary": "Process\u0020the\u0020controller\u0020and\u0020get\u0020the\u0020output\u0020content.",
            "url": "classes/Rdb-System-App.html#method_processController"
        },                {
            "fqsen": "\\Rdb\\System\\App\u003A\u003AprocessHeaders\u0028\u0029",
            "name": "processHeaders",
            "summary": "Process\u0020headers.",
            "url": "classes/Rdb-System-App.html#method_processHeaders"
        },                {
            "fqsen": "\\Rdb\\System\\App\u003A\u003AprocessRoute\u0028\u0029",
            "name": "processRoute",
            "summary": "Process\u0020route.",
            "url": "classes/Rdb-System-App.html#method_processRoute"
        },                {
            "fqsen": "\\Rdb\\System\\App\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Run\u0020the\u0020application.",
            "url": "classes/Rdb-System-App.html#method_run"
        },                {
            "fqsen": "\\Rdb\\System\\App\u003A\u003A\u0024Config",
            "name": "Config",
            "summary": "",
            "url": "classes/Rdb-System-App.html#property_Config"
        },                {
            "fqsen": "\\Rdb\\System\\App\u003A\u003A\u0024Container",
            "name": "Container",
            "summary": "",
            "url": "classes/Rdb-System-App.html#property_Container"
        },                {
            "fqsen": "\\Rdb\\System\\App\u003A\u003A\u0024Logger",
            "name": "Logger",
            "summary": "",
            "url": "classes/Rdb-System-App.html#property_Logger"
        },                {
            "fqsen": "\\Rdb\\System\\Cli",
            "name": "Cli",
            "summary": "CLI\u0020class.",
            "url": "classes/Rdb-System-Cli.html"
        },                {
            "fqsen": "\\Rdb\\System\\Cli\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Class\u0020constructor.",
            "url": "classes/Rdb-System-Cli.html#method___construct"
        },                {
            "fqsen": "\\Rdb\\System\\Cli\u003A\u003AgetAvailableCommands\u0028\u0029",
            "name": "getAvailableCommands",
            "summary": "Automatic\u0020get\u0020all\u0020available\u0020commands\u0020in\u0020Rdb\\System\\Core\\Console\u0020and\u0020Rdb\\Modules\\\u005BModuleName\u005D\\Console",
            "url": "classes/Rdb-System-Cli.html#method_getAvailableCommands"
        },                {
            "fqsen": "\\Rdb\\System\\Cli\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Run\u0020the\u0020application\u0020in\u0020command\u0020line.",
            "url": "classes/Rdb-System-Cli.html#method_run"
        },                {
            "fqsen": "\\Rdb\\System\\Cli\u003A\u003A\u0024CliApp",
            "name": "CliApp",
            "summary": "",
            "url": "classes/Rdb-System-Cli.html#property_CliApp"
        },                {
            "fqsen": "\\Rdb\\System\\Cli\u003A\u003A\u0024Container",
            "name": "Container",
            "summary": "",
            "url": "classes/Rdb-System-Cli.html#property_Container"
        },                {
            "fqsen": "\\Rdb\\System\\Config",
            "name": "Config",
            "summary": "Load\u0020config\u0020files\u0020from\u0020\/config\u0020folder\u0020from\u0020main\u0020application\u0020or\u0020modules\u0020in\u0020each\u0020environment\u0020that\u0020was\u0020set\u0020in\u0020the\u0020\/public\/index.php\u0020file.",
            "url": "classes/Rdb-System-Config.html"
        },                {
            "fqsen": "\\Rdb\\System\\Config\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Config\u0020class\u0020constructor.",
            "url": "classes/Rdb-System-Config.html#method___construct"
        },                {
            "fqsen": "\\Rdb\\System\\Config\u003A\u003A__get\u0028\u0029",
            "name": "__get",
            "summary": "Magic\u0020get.",
            "url": "classes/Rdb-System-Config.html#method___get"
        },                {
            "fqsen": "\\Rdb\\System\\Config\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Get\u0020the\u0020config\u0020value\u0020from\u0020specified\u0020name.",
            "url": "classes/Rdb-System-Config.html#method_get"
        },                {
            "fqsen": "\\Rdb\\System\\Config\u003A\u003AgetFile\u0028\u0029",
            "name": "getFile",
            "summary": "Get\u0020path\u0020to\u0020config\u0020file\u0020depend\u0020on\u0020environment\u0020and\u0020file\u0020that\u0020exists.",
            "url": "classes/Rdb-System-Config.html#method_getFile"
        },                {
            "fqsen": "\\Rdb\\System\\Config\u003A\u003AgetDefaultLanguage\u0028\u0029",
            "name": "getDefaultLanguage",
            "summary": "Get\u0020default\u0020language.",
            "url": "classes/Rdb-System-Config.html#method_getDefaultLanguage"
        },                {
            "fqsen": "\\Rdb\\System\\Config\u003A\u003AgetWithoutCache\u0028\u0029",
            "name": "getWithoutCache",
            "summary": "Get\u0020the\u0020config\u0020value\u0020from\u0020specified\u0020name.",
            "url": "classes/Rdb-System-Config.html#method_getWithoutCache"
        },                {
            "fqsen": "\\Rdb\\System\\Config\u003A\u003AisLoaded\u0028\u0029",
            "name": "isLoaded",
            "summary": "Check\u0020if\u0020config\u0020file\u0020was\u0020loaded.\u0020If\u0020config\u0020file\u0020was\u0020not\u0020loaded,\u0020load\u0020the\u0020config\u0020file.",
            "url": "classes/Rdb-System-Config.html#method_isLoaded"
        },                {
            "fqsen": "\\Rdb\\System\\Config\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "Load\u0020the\u0020config\u0020file\u0020into\u0020property\u0020array.",
            "url": "classes/Rdb-System-Config.html#method_load"
        },                {
            "fqsen": "\\Rdb\\System\\Config\u003A\u003Aset\u0028\u0029",
            "name": "set",
            "summary": "Set\u0020config\u0020name\u0020\u0028key\u0029\u0020and\u0020value\u0020to\u0020an\u0020existing\u0020config\u0020file.",
            "url": "classes/Rdb-System-Config.html#method_set"
        },                {
            "fqsen": "\\Rdb\\System\\Config\u003A\u003AsetModule\u0028\u0029",
            "name": "setModule",
            "summary": "Set\u0020the\u0020module\u0020that\u0020this\u0020class\u0020will\u0020be\u0020get\u0020config\u0020from\u0020it.",
            "url": "classes/Rdb-System-Config.html#method_setModule"
        },                {
            "fqsen": "\\Rdb\\System\\Config\u003A\u003A\u0024loadedFiles",
            "name": "loadedFiles",
            "summary": "",
            "url": "classes/Rdb-System-Config.html#property_loadedFiles"
        },                {
            "fqsen": "\\Rdb\\System\\Config\u003A\u003A\u0024moduleSystemName",
            "name": "moduleSystemName",
            "summary": "",
            "url": "classes/Rdb-System-Config.html#property_moduleSystemName"
        },                {
            "fqsen": "\\Rdb\\System\\Config\u003A\u003A\u0024traceLoadedFiles",
            "name": "traceLoadedFiles",
            "summary": "",
            "url": "classes/Rdb-System-Config.html#property_traceLoadedFiles"
        },                {
            "fqsen": "\\Rdb\\System\\Container",
            "name": "Container",
            "summary": "Dependency\u0020injection\u0020container.",
            "url": "classes/Rdb-System-Container.html"
        },                {
            "fqsen": "\\Rdb\\System\\Container\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "\u007B\u0040inheritDoc\u007D",
            "url": "classes/Rdb-System-Container.html#method___construct"
        },                {
            "fqsen": "\\Rdb\\System\\Container\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "\u007B\u0040inheritDoc\u007D",
            "url": "classes/Rdb-System-Container.html#method_get"
        },                {
            "fqsen": "\\Rdb\\System\\Container\u003A\u003Ahas\u0028\u0029",
            "name": "has",
            "summary": "\u007B\u0040inheritDoc\u007D",
            "url": "classes/Rdb-System-Container.html#method_has"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Console\\BaseConsole",
            "name": "BaseConsole",
            "summary": "Base\u0020console\u0020\u0028CLI\u0029\u0020class.",
            "url": "classes/Rdb-System-Core-Console-BaseConsole.html"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Console\\BaseConsole\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Class\u0020constructor.",
            "url": "classes/Rdb-System-Core-Console-BaseConsole.html#method___construct"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Console\\BaseConsole\u003A\u003A\u0024Container",
            "name": "Container",
            "summary": "",
            "url": "classes/Rdb-System-Core-Console-BaseConsole.html#property_Container"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Console\\Constants",
            "name": "Constants",
            "summary": "Module\u0020CLI.",
            "url": "classes/Rdb-System-Core-Console-Constants.html"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Console\\Constants\u003A\u003Aconfigure\u0028\u0029",
            "name": "configure",
            "summary": "\u007B\u0040inheritDoc\u007D",
            "url": "classes/Rdb-System-Core-Console-Constants.html#method_configure"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Console\\Constants\u003A\u003AconvertConstantValueString\u0028\u0029",
            "name": "convertConstantValueString",
            "summary": "Convert\u0020constant\u0020value\u0020to\u0020string.",
            "url": "classes/Rdb-System-Core-Console-Constants.html#method_convertConstantValueString"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Console\\Constants\u003A\u003Aexecute\u0028\u0029",
            "name": "execute",
            "summary": "\u007B\u0040inheritDoc\u007D",
            "url": "classes/Rdb-System-Core-Console-Constants.html#method_execute"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Console\\Constants\u003A\u003AexecuteAllConstants\u0028\u0029",
            "name": "executeAllConstants",
            "summary": "Display\u0020all\u0020constants.",
            "url": "classes/Rdb-System-Core-Console-Constants.html#method_executeAllConstants"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Console\\Constants\u003A\u003AexecuteSpecificConstantGroup\u0028\u0029",
            "name": "executeSpecificConstantGroup",
            "summary": "Display\u0020specific\u0020constant\u0020group.",
            "url": "classes/Rdb-System-Core-Console-Constants.html#method_executeSpecificConstantGroup"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Console\\Constants\u003A\u003AexecuteSpecificConstantName\u0028\u0029",
            "name": "executeSpecificConstantName",
            "summary": "Display\u0020specific\u0020constant\u0020name.",
            "url": "classes/Rdb-System-Core-Console-Constants.html#method_executeSpecificConstantName"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Console\\Module",
            "name": "Module",
            "summary": "Module\u0020CLI.",
            "url": "classes/Rdb-System-Core-Console-Module.html"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Console\\Module\u003A\u003Aconfigure\u0028\u0029",
            "name": "configure",
            "summary": "\u007B\u0040inheritDoc\u007D",
            "url": "classes/Rdb-System-Core-Console-Module.html#method_configure"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Console\\Module\u003A\u003AdisplaySuccess\u0028\u0029",
            "name": "displaySuccess",
            "summary": "Display\u0020success\u0020message\u0020with\u0020additional\u0020message\u0020\u0028if\u0020exists\u0029.",
            "url": "classes/Rdb-System-Core-Console-Module.html#method_displaySuccess"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Console\\Module\u003A\u003Aexecute\u0028\u0029",
            "name": "execute",
            "summary": "\u007B\u0040inheritDoc\u007D",
            "url": "classes/Rdb-System-Core-Console-Module.html#method_execute"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Console\\Module\u003A\u003AexecuteDisable\u0028\u0029",
            "name": "executeDisable",
            "summary": "Disable\u0020a\u0020module.",
            "url": "classes/Rdb-System-Core-Console-Module.html#method_executeDisable"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Console\\Module\u003A\u003AexecuteEnable\u0028\u0029",
            "name": "executeEnable",
            "summary": "Enable\u0020a\u0020module.",
            "url": "classes/Rdb-System-Core-Console-Module.html#method_executeEnable"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Console\\Module\u003A\u003AexecuteInstall\u0028\u0029",
            "name": "executeInstall",
            "summary": "Install\u0020a\u0020module.",
            "url": "classes/Rdb-System-Core-Console-Module.html#method_executeInstall"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Console\\Module\u003A\u003AexecuteUninstall\u0028\u0029",
            "name": "executeUninstall",
            "summary": "Uninstall\u0020a\u0020module.",
            "url": "classes/Rdb-System-Core-Console-Module.html#method_executeUninstall"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Console\\Module\u003A\u003AexecuteUpdate\u0028\u0029",
            "name": "executeUpdate",
            "summary": "Update\u0020a\u0020module.",
            "url": "classes/Rdb-System-Core-Console-Module.html#method_executeUpdate"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Console\\Module\u003A\u003AisTargetFileFolderWritable\u0028\u0029",
            "name": "isTargetFileFolderWritable",
            "summary": "Check\u0020if\u0020target\u0020file\u0020and\u0020folder\u0020is\u0020writable.",
            "url": "classes/Rdb-System-Core-Console-Module.html#method_isTargetFileFolderWritable"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Console\\Module\u003A\u003A\u0024Modules",
            "name": "Modules",
            "summary": "",
            "url": "classes/Rdb-System-Core-Console-Module.html#property_Modules"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Console\\Phinx\\Phinx",
            "name": "Phinx",
            "summary": "Phinx\u0020CLI",
            "url": "classes/Rdb-System-Core-Console-Phinx-Phinx.html"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Console\\Phinx\\Phinx\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Class\u0020constructor.",
            "url": "classes/Rdb-System-Core-Console-Phinx-Phinx.html#method___construct"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Console\\Phinx\\Phinx\u003A\u003AIncludeExternalCommands\u0028\u0029",
            "name": "IncludeExternalCommands",
            "summary": "Include\u0020external\u0020commands",
            "url": "classes/Rdb-System-Core-Console-Phinx-Phinx.html#method_IncludeExternalCommands"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Console\\Phinx\\Phinx\u003A\u003A\u0024PhinxApplication",
            "name": "PhinxApplication",
            "summary": "",
            "url": "classes/Rdb-System-Core-Console-Phinx-Phinx.html#property_PhinxApplication"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Console\\Storage",
            "name": "Storage",
            "summary": "Storage\u0020CLI.",
            "url": "classes/Rdb-System-Core-Console-Storage.html"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Console\\Storage\u003A\u003Aconfigure\u0028\u0029",
            "name": "configure",
            "summary": "\u007B\u0040inheritDoc\u007D",
            "url": "classes/Rdb-System-Core-Console-Storage.html#method_configure"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Console\\Storage\u003A\u003Aexecute\u0028\u0029",
            "name": "execute",
            "summary": "\u007B\u0040inheritDoc\u007D",
            "url": "classes/Rdb-System-Core-Console-Storage.html#method_execute"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Console\\Storage\u003A\u003AexecuteClear\u0028\u0029",
            "name": "executeClear",
            "summary": "Clear\u0020storage\u0020folder.\u0020\u0028delete\u0020cache,\u0020logs\u0020folders.\u0029",
            "url": "classes/Rdb-System-Core-Console-Storage.html#method_executeClear"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Console\\Storage\u003A\u003AexecuteClearDelete\u0028\u0029",
            "name": "executeClearDelete",
            "summary": "Do\u0020clear\u0020target\u0020folder.",
            "url": "classes/Rdb-System-Core-Console-Storage.html#method_executeClearDelete"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Console\\Storage\u003A\u003AexecuteDelete\u0028\u0029",
            "name": "executeDelete",
            "summary": "Delete\u0020folders\u0020and\u0020files.",
            "url": "classes/Rdb-System-Core-Console-Storage.html#method_executeDelete"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Console\\Storage\u003A\u003AexecuteList\u0028\u0029",
            "name": "executeList",
            "summary": "List\u0020folders\u0020and\u0020files.",
            "url": "classes/Rdb-System-Core-Console-Storage.html#method_executeList"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Console\\Storage\u003A\u003ArenderTableFiles\u0028\u0029",
            "name": "renderTableFiles",
            "summary": "Render\u0020files\u0020to\u0020table.",
            "url": "classes/Rdb-System-Core-Console-Storage.html#method_renderTableFiles"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Console\\Storage\u003A\u003A\u0024FileSystem",
            "name": "FileSystem",
            "summary": "",
            "url": "classes/Rdb-System-Core-Console-Storage.html#property_FileSystem"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Controllers\\BaseController",
            "name": "BaseController",
            "summary": "BasedController\u0020class.",
            "url": "classes/Rdb-System-Core-Controllers-BaseController.html"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Controllers\\BaseController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Based\u0020controller.",
            "url": "classes/Rdb-System-Core-Controllers-BaseController.html#method___construct"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Controllers\\BaseController\u003A\u003AdetermineAcceptContentType\u0028\u0029",
            "name": "determineAcceptContentType",
            "summary": "Determine\u0020HTTP\u0020accept\u0020content\u002Dtype.",
            "url": "classes/Rdb-System-Core-Controllers-BaseController.html#method_determineAcceptContentType"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Controllers\\BaseController\u003A\u003AresponseAcceptType\u0028\u0029",
            "name": "responseAcceptType",
            "summary": "Response\u0020the\u0020\u0060\u0024output\u0060\u0020content\u0020by\u0020\u0060accept\u0060\u0020type\u0020in\u0020request\u0020header.",
            "url": "classes/Rdb-System-Core-Controllers-BaseController.html#method_responseAcceptType"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Controllers\\BaseController\u003A\u003AresponseJson\u0028\u0029",
            "name": "responseJson",
            "summary": "Set\u0020application\/json\u0020header\u0020and\u0020return\u0020json\u0020encoded.",
            "url": "classes/Rdb-System-Core-Controllers-BaseController.html#method_responseJson"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Controllers\\BaseController\u003A\u003AresponseNoCache\u0028\u0029",
            "name": "responseNoCache",
            "summary": "Send\u0020no\u0020cache\u0020headers.",
            "url": "classes/Rdb-System-Core-Controllers-BaseController.html#method_responseNoCache"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Controllers\\BaseController\u003A\u003AresponseXml\u0028\u0029",
            "name": "responseXml",
            "summary": "Set\u0020application\/xml\u0020header\u0020and\u0020return\u0020XML\u0020converted\u0020from\u0020array.",
            "url": "classes/Rdb-System-Core-Controllers-BaseController.html#method_responseXml"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Controllers\\BaseController\u003A\u003A\u0024Container",
            "name": "Container",
            "summary": "",
            "url": "classes/Rdb-System-Core-Controllers-BaseController.html#property_Container"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Controllers\\BaseController\u003A\u003A\u0024Db",
            "name": "Db",
            "summary": "",
            "url": "classes/Rdb-System-Core-Controllers-BaseController.html#property_Db"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Controllers\\BaseController\u003A\u003A\u0024httpAcceptContentTypes",
            "name": "httpAcceptContentTypes",
            "summary": "",
            "url": "classes/Rdb-System-Core-Controllers-BaseController.html#property_httpAcceptContentTypes"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Controllers\\BaseController\u003A\u003A\u0024Modules",
            "name": "Modules",
            "summary": "",
            "url": "classes/Rdb-System-Core-Controllers-BaseController.html#property_Modules"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Controllers\\BaseController\u003A\u003A\u0024Views",
            "name": "Views",
            "summary": "",
            "url": "classes/Rdb-System-Core-Controllers-BaseController.html#property_Views"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Controllers\\DefaultController",
            "name": "DefaultController",
            "summary": "DefaultController",
            "url": "classes/Rdb-System-Core-Controllers-DefaultController.html"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Controllers\\DefaultController\u003A\u003AindexAction\u0028\u0029",
            "name": "indexAction",
            "summary": "Default\u0020action\u0020for\u0020controller.",
            "url": "classes/Rdb-System-Core-Controllers-DefaultController.html#method_indexAction"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Controllers\\Error\\E404Controller",
            "name": "E404Controller",
            "summary": "Error\u0020404\u0020controller.",
            "url": "classes/Rdb-System-Core-Controllers-Error-E404Controller.html"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Controllers\\Error\\E404Controller\u003A\u003AindexAction\u0028\u0029",
            "name": "indexAction",
            "summary": "Response\u0020not\u0020found\u0020message\u0020by\u0020content\u0020type.",
            "url": "classes/Rdb-System-Core-Controllers-Error-E404Controller.html#method_indexAction"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Controllers\\Error\\E405Controller",
            "name": "E405Controller",
            "summary": "Error\u0020405\u0020controller.",
            "url": "classes/Rdb-System-Core-Controllers-Error-E405Controller.html"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Controllers\\Error\\E405Controller\u003A\u003AindexAction\u0028\u0029",
            "name": "indexAction",
            "summary": "Response\u0020method\u0020not\u0020allowed\u0020message\u0020by\u0020content\u0020type.",
            "url": "classes/Rdb-System-Core-Controllers-Error-E405Controller.html#method_indexAction"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Models\\BaseModel",
            "name": "BaseModel",
            "summary": "Base\u0020model\u0020DB.",
            "url": "classes/Rdb-System-Core-Models-BaseModel.html"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Models\\BaseModel\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Base\u0020model\u0020class\u0020constructor.",
            "url": "classes/Rdb-System-Core-Models-BaseModel.html#method___construct"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Models\\BaseModel\u003A\u003A\u0024allowedOrders",
            "name": "allowedOrders",
            "summary": "Allowed\u0020orders\u0020in\u0020MySQL,\u0020MariaDB.",
            "url": "classes/Rdb-System-Core-Models-BaseModel.html#property_allowedOrders"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Models\\BaseModel\u003A\u003A\u0024Container",
            "name": "Container",
            "summary": "",
            "url": "classes/Rdb-System-Core-Models-BaseModel.html#property_Container"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Models\\BaseModel\u003A\u003A\u0024Db",
            "name": "Db",
            "summary": "",
            "url": "classes/Rdb-System-Core-Models-BaseModel.html#property_Db"
        },                {
            "fqsen": "\\str_contains\u0028\u0029",
            "name": "str_contains",
            "summary": "Performs\u0020a\u0020case\u002Dsensitive\u0020check\u0020indicating\u0020if\u0020needle\u0020is\u0020contained\u0020in\u0020haystack.",
            "url": "namespaces/default.html#function_str_contains"
        },                {
            "fqsen": "\\Rdb\\System\\Interfaces\\ModuleInstaller",
            "name": "ModuleInstaller",
            "summary": "Module\u0020installer\u0020interface.",
            "url": "classes/Rdb-System-Interfaces-ModuleInstaller.html"
        },                {
            "fqsen": "\\Rdb\\System\\Interfaces\\ModuleInstaller\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "The\u0020class\u0020constructor.",
            "url": "classes/Rdb-System-Interfaces-ModuleInstaller.html#method___construct"
        },                {
            "fqsen": "\\Rdb\\System\\Interfaces\\ModuleInstaller\u003A\u003Ainstall\u0028\u0029",
            "name": "install",
            "summary": "Install\u0020a\u0020module.",
            "url": "classes/Rdb-System-Interfaces-ModuleInstaller.html#method_install"
        },                {
            "fqsen": "\\Rdb\\System\\Interfaces\\ModuleInstaller\u003A\u003Auninstall\u0028\u0029",
            "name": "uninstall",
            "summary": "Uninstall\u0020a\u0020module.",
            "url": "classes/Rdb-System-Interfaces-ModuleInstaller.html#method_uninstall"
        },                {
            "fqsen": "\\Rdb\\System\\Interfaces\\ModuleInstaller\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Update\u0020a\u0020module.",
            "url": "classes/Rdb-System-Interfaces-ModuleInstaller.html#method_update"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\ArrayUtil",
            "name": "ArrayUtil",
            "summary": "Array\u0020utilities\u0020class.",
            "url": "classes/Rdb-System-Libraries-ArrayUtil.html"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\ArrayUtil\u003A\u003A__callStatic\u0028\u0029",
            "name": "__callStatic",
            "summary": "Call\u0020static\u0020magic\u0020method.",
            "url": "classes/Rdb-System-Libraries-ArrayUtil.html#method___callStatic"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\ArrayUtil\u003A\u003AarrayCustomMerge\u0028\u0029",
            "name": "arrayCustomMerge",
            "summary": "Array\u0020custom\u0020merge.\u0020Preserve\u0020indexed\u0020array\u0020key\u0020\u0028numbers\u0029\u0020but\u0020overwrite\u0020string\u0020key\u0020\u0028same\u0020as\u0020PHP\u0027s\u0020\u0060array_merge\u0028\u0029\u0060\u0020function\u0029.",
            "url": "classes/Rdb-System-Libraries-ArrayUtil.html#method_arrayCustomMerge"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\ArrayUtil\u003A\u003AinArrayI\u0028\u0029",
            "name": "inArrayI",
            "summary": "Checks\u0020if\u0020a\u0020value\u0020exists\u0020in\u0020an\u0020array\u0020\u0028case\u0020insensitive\u0029.",
            "url": "classes/Rdb-System-Libraries-ArrayUtil.html#method_inArrayI"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\ArrayUtil\u003A\u003AisAssoc\u0028\u0029",
            "name": "isAssoc",
            "summary": "Check\u0020if\u0020associative\u0020array\u0020or\u0020indexed\u0020array\u003F",
            "url": "classes/Rdb-System-Libraries-ArrayUtil.html#method_isAssoc"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\ArrayUtil\u003A\u003ArecursiveKsort\u0028\u0029",
            "name": "recursiveKsort",
            "summary": "Recursive\u0020sort\u0020array\u0020key.",
            "url": "classes/Rdb-System-Libraries-ArrayUtil.html#method_recursiveKsort"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\ArrayUtil\u003A\u003AstaticRecursiveKsort\u0028\u0029",
            "name": "staticRecursiveKsort",
            "summary": "Static\u0020version\u0020of\u0020\u0060recursiveKsort\u0028\u0029\u0060.",
            "url": "classes/Rdb-System-Libraries-ArrayUtil.html#method_staticRecursiveKsort"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Db\\Logger",
            "name": "Logger",
            "summary": "DB\u0020Logger\u0020class.",
            "url": "classes/Rdb-System-Libraries-Db-Logger.html"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Db\\Logger\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Class\u0020constructor.",
            "url": "classes/Rdb-System-Libraries-Db-Logger.html#method___construct"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Db\\Logger\u003A\u003AqueryLog\u0028\u0029",
            "name": "queryLog",
            "summary": "Log\u0020the\u0020DB\u0020statement\u0020query.",
            "url": "classes/Rdb-System-Libraries-Db-Logger.html#method_queryLog"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Db\\Logger\u003A\u003A\u0024Container",
            "name": "Container",
            "summary": "",
            "url": "classes/Rdb-System-Libraries-Db-Logger.html#property_Container"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Db\\Statement",
            "name": "Statement",
            "summary": "DB\u0020statement\u0020class.",
            "url": "classes/Rdb-System-Libraries-Db-Statement.html"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Db\\Statement\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Class\u0020constructor\u0020is\u0020required.",
            "url": "classes/Rdb-System-Libraries-Db-Statement.html#method___construct"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Db\\Statement\u003A\u003AbindParam\u0028\u0029",
            "name": "bindParam",
            "summary": "\u007B\u0040inheritDoc\u007D",
            "url": "classes/Rdb-System-Libraries-Db-Statement.html#method_bindParam"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Db\\Statement\u003A\u003AbindValue\u0028\u0029",
            "name": "bindValue",
            "summary": "\u007B\u0040inheritDoc\u007D",
            "url": "classes/Rdb-System-Libraries-Db-Statement.html#method_bindValue"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Db\\Statement\u003A\u003Aexecute\u0028\u0029",
            "name": "execute",
            "summary": "\u007B\u0040inheritDoc\u007D",
            "url": "classes/Rdb-System-Libraries-Db-Statement.html#method_execute"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Db\\Statement\u003A\u003A\u0024Container",
            "name": "Container",
            "summary": "",
            "url": "classes/Rdb-System-Libraries-Db-Statement.html#property_Container"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Db\\Statement\u003A\u003A\u0024inputDataTypes",
            "name": "inputDataTypes",
            "summary": "",
            "url": "classes/Rdb-System-Libraries-Db-Statement.html#property_inputDataTypes"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Db\\Statement\u003A\u003A\u0024inputParams",
            "name": "inputParams",
            "summary": "",
            "url": "classes/Rdb-System-Libraries-Db-Statement.html#property_inputParams"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Db",
            "name": "Db",
            "summary": "Database\u0020class\u0020that\u0020is\u0020working\u0020on\u0020PDO.",
            "url": "classes/Rdb-System-Libraries-Db.html"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Db\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "DB\u0020class\u0020constructor.",
            "url": "classes/Rdb-System-Libraries-Db.html#method___construct"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Db\u003A\u003A__destruct\u0028\u0029",
            "name": "__destruct",
            "summary": "Class\u0020de\u002Dconstructor.",
            "url": "classes/Rdb-System-Libraries-Db.html#method___destruct"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Db\u003A\u003AalterStructure\u0028\u0029",
            "name": "alterStructure",
            "summary": "Alter\u0020DB\u0020table\u0020structure.",
            "url": "classes/Rdb-System-Libraries-Db.html#method_alterStructure"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Db\u003A\u003AbuildPlaceholdersAndValues\u0028\u0029",
            "name": "buildPlaceholdersAndValues",
            "summary": "Build\u0020placeholders\u0020and\u0020its\u0020values.",
            "url": "classes/Rdb-System-Libraries-Db.html#method_buildPlaceholdersAndValues"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Db\u003A\u003Aconnect\u0028\u0029",
            "name": "connect",
            "summary": "Create\u0020a\u0020connection\u0020with\u0020connection\u0020key\u0020in\u0020the\u0020\u0060db\u0060\u0020configuration\u0020file.",
            "url": "classes/Rdb-System-Libraries-Db.html#method_connect"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Db\u003A\u003AconvertCharsetAndCollation\u0028\u0029",
            "name": "convertCharsetAndCollation",
            "summary": "Convert\u0020character\u0020set\u0020and\u0020collation\u0020for\u0020table\u0020and\u0020columns.",
            "url": "classes/Rdb-System-Libraries-Db.html#method_convertCharsetAndCollation"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Db\u003A\u003A\u0024currentConnectionKey",
            "name": "currentConnectionKey",
            "summary": "",
            "url": "classes/Rdb-System-Libraries-Db.html#property_currentConnectionKey"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Db\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "Delete\u0020data\u0020from\u0020DB\u0020table.",
            "url": "classes/Rdb-System-Libraries-Db.html#method_delete"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Db\u003A\u003Adisconnect\u0028\u0029",
            "name": "disconnect",
            "summary": "Disconnect\u0020from\u0020DB\u0020on\u0020specific\u0020connection\u0020key.",
            "url": "classes/Rdb-System-Libraries-Db.html#method_disconnect"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Db\u003A\u003AdisconnectAll\u0028\u0029",
            "name": "disconnectAll",
            "summary": "Disconnect\u0020from\u0020DB\u0020on\u0020all\u0020connections.",
            "url": "classes/Rdb-System-Libraries-Db.html#method_disconnectAll"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Db\u003A\u003Aexec\u0028\u0029",
            "name": "exec",
            "summary": "Execute\u0020an\u0020SQL\u0020statement\u0020and\u0020return\u0020the\u0020number\u0020of\u0020affected\u0020rows.",
            "url": "classes/Rdb-System-Libraries-Db.html#method_exec"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Db\u003A\u003Ainsert\u0028\u0029",
            "name": "insert",
            "summary": "Insert\u0020data\u0020into\u0020DB\u0020table.",
            "url": "classes/Rdb-System-Libraries-Db.html#method_insert"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Db\u003A\u003A\u0024PDO",
            "name": "PDO",
            "summary": "",
            "url": "classes/Rdb-System-Libraries-Db.html#property_PDO"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Db\u003A\u003APDOStatement\u0028\u0029",
            "name": "PDOStatement",
            "summary": "Get\u0020PDO\u0020statement\u0020after\u0020called\u0020\u0060insert\u0028\u0029\u0060,\u0020\u0060update\u0028\u0029\u0060,\u0020\u0060delete\u0028\u0029\u0060.",
            "url": "classes/Rdb-System-Libraries-Db.html#method_PDOStatement"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Db\u003A\u003Aquery\u0028\u0029",
            "name": "query",
            "summary": "Executes\u0020an\u0020SQL\u0020statement,\u0020returning\u0020a\u0020result\u0020set\u0020as\u0020a\u0020PDOStatement\u0020object.",
            "url": "classes/Rdb-System-Libraries-Db.html#method_query"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Db\u003A\u003AremoveSQLComments\u0028\u0029",
            "name": "removeSQLComments",
            "summary": "Remove\u0020any\u0020comments\u0020from\u0020statement.",
            "url": "classes/Rdb-System-Libraries-Db.html#method_removeSQLComments"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Db\u003A\u003AsetCurrentConnectionKey\u0028\u0029",
            "name": "setCurrentConnectionKey",
            "summary": "Set\u0020current\u0020connection\u0020key\u0020to\u0020the\u0020new\u0020key.",
            "url": "classes/Rdb-System-Libraries-Db.html#method_setCurrentConnectionKey"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Db\u003A\u003AtableName\u0028\u0029",
            "name": "tableName",
            "summary": "Get\u0020table\u0020name\u0020with\u0020prefix\u0020based\u0020on\u0020configuration\u0020for\u0020specific\u0020connection\u0020key.",
            "url": "classes/Rdb-System-Libraries-Db.html#method_tableName"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Db\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Update\u0020data\u0020into\u0020DB\u0020table.",
            "url": "classes/Rdb-System-Libraries-Db.html#method_update"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Db\u003A\u003A\u0024Config",
            "name": "Config",
            "summary": "",
            "url": "classes/Rdb-System-Libraries-Db.html#property_Config"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Db\u003A\u003A\u0024Container",
            "name": "Container",
            "summary": "",
            "url": "classes/Rdb-System-Libraries-Db.html#property_Container"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Db\u003A\u003A\u0024Sth",
            "name": "Sth",
            "summary": "",
            "url": "classes/Rdb-System-Libraries-Db.html#property_Sth"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\FileSystem",
            "name": "FileSystem",
            "summary": "Works\u0020about\u0020files\u0020and\u0020folders.",
            "url": "classes/Rdb-System-Libraries-FileSystem.html"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\FileSystem\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Class\u0020constructor.",
            "url": "classes/Rdb-System-Libraries-FileSystem.html#method___construct"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\FileSystem\u003A\u003AcopyFolderRecursive\u0028\u0029",
            "name": "copyFolderRecursive",
            "summary": "Copy\u0020folder\u0020recursively.",
            "url": "classes/Rdb-System-Libraries-FileSystem.html#method_copyFolderRecursive"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\FileSystem\u003A\u003AcreateFile\u0028\u0029",
            "name": "createFile",
            "summary": "Create\u0020new\u0020file.",
            "url": "classes/Rdb-System-Libraries-FileSystem.html#method_createFile"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\FileSystem\u003A\u003AcreateFolder\u0028\u0029",
            "name": "createFolder",
            "summary": "Create\u0020folder.",
            "url": "classes/Rdb-System-Libraries-FileSystem.html#method_createFolder"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\FileSystem\u003A\u003AdeleteFile\u0028\u0029",
            "name": "deleteFile",
            "summary": "Delete\u0020a\u0020file.",
            "url": "classes/Rdb-System-Libraries-FileSystem.html#method_deleteFile"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\FileSystem\u003A\u003AdeleteFolder\u0028\u0029",
            "name": "deleteFolder",
            "summary": "Delete\u0020folder\u0020and\u0020its\u0020content.",
            "url": "classes/Rdb-System-Libraries-FileSystem.html#method_deleteFolder"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\FileSystem\u003A\u003AgetBase64File\u0028\u0029",
            "name": "getBase64File",
            "summary": "Get\u0020base\u002064\u0020string\u0020from\u0020file\u0020name.",
            "url": "classes/Rdb-System-Libraries-FileSystem.html#method_getBase64File"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\FileSystem\u003A\u003AgetFileExtensionOnly\u0028\u0029",
            "name": "getFileExtensionOnly",
            "summary": "Get\u0020file\u0020extension\u0020only.",
            "url": "classes/Rdb-System-Libraries-FileSystem.html#method_getFileExtensionOnly"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\FileSystem\u003A\u003AgetFileNameExtension\u0028\u0029",
            "name": "getFileNameExtension",
            "summary": "Get\u0020file\u0020name\u0020with\u0020extension.\u0020No\u0020path\u0020included.",
            "url": "classes/Rdb-System-Libraries-FileSystem.html#method_getFileNameExtension"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\FileSystem\u003A\u003AgetFileNameOnly\u0028\u0029",
            "name": "getFileNameOnly",
            "summary": "Get\u0020file\u0020name\u0020only.",
            "url": "classes/Rdb-System-Libraries-FileSystem.html#method_getFileNameOnly"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\FileSystem\u003A\u003AgetFolderSize\u0028\u0029",
            "name": "getFolderSize",
            "summary": "Get\u0020total\u0020folder\u0020size.",
            "url": "classes/Rdb-System-Libraries-FileSystem.html#method_getFolderSize"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\FileSystem\u003A\u003AgetFullPathWithRoot\u0028\u0029",
            "name": "getFullPathWithRoot",
            "summary": "Connect\u0020the\u0020specify\u0020path\u0020with\u0020root\u0020on\u0020constructor\u0020and\u0020get\u0020its\u0020full\u0020path.",
            "url": "classes/Rdb-System-Libraries-FileSystem.html#method_getFullPathWithRoot"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\FileSystem\u003A\u003AgetTimestamp\u0028\u0029",
            "name": "getTimestamp",
            "summary": "Get\u0020file\u0020or\u0020folder\u0020timestamp.",
            "url": "classes/Rdb-System-Libraries-FileSystem.html#method_getTimestamp"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\FileSystem\u003A\u003AisDir\u0028\u0029",
            "name": "isDir",
            "summary": "Check\u0020for\u0020is\u0020file\u0020exists\u0020and\u0020it\u0020is\u0020folder\u0020\u0028or\u0020directory\u0029.",
            "url": "classes/Rdb-System-Libraries-FileSystem.html#method_isDir"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\FileSystem\u003A\u003AisFile\u0028\u0029",
            "name": "isFile",
            "summary": "Check\u0020for\u0020is\u0020file\u0020exists\u0020and\u0020it\u0020is\u0020file.",
            "url": "classes/Rdb-System-Libraries-FileSystem.html#method_isFile"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\FileSystem\u003A\u003AlistFiles\u0028\u0029",
            "name": "listFiles",
            "summary": "List\u0020all\u0020files\u0020only,\u0020folders\u0020only,\u0020files\u0020and\u0020folders\u0020in\u0020single\u0020level\u0020of\u0020specified\u0020\u0024dirname.",
            "url": "classes/Rdb-System-Libraries-FileSystem.html#method_listFiles"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\FileSystem\u003A\u003AlistFilesSubFolders\u0028\u0029",
            "name": "listFilesSubFolders",
            "summary": "List\u0020all\u0020files\u0020and\u0020subfolders\u0020in\u0020specified\u0020\u0024dirname.",
            "url": "classes/Rdb-System-Libraries-FileSystem.html#method_listFilesSubFolders"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\FileSystem\u003A\u003AremoveUpperPath\u0028\u0029",
            "name": "removeUpperPath",
            "summary": "Remove\u0020any\u0020upper\u0020path\u0020string\u0020such\u0020as\u0020..\/\u0020from\u0020string.",
            "url": "classes/Rdb-System-Libraries-FileSystem.html#method_removeUpperPath"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\FileSystem\u003A\u003Arename\u0028\u0029",
            "name": "rename",
            "summary": "Rename\u0020a\u0020file\u0020or\u0020directory.",
            "url": "classes/Rdb-System-Libraries-FileSystem.html#method_rename"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\FileSystem\u003A\u003AsetWebSafeFileName\u0028\u0029",
            "name": "setWebSafeFileName",
            "summary": "Set\u0020web\u0020safe\u0020file\u0020name.",
            "url": "classes/Rdb-System-Libraries-FileSystem.html#method_setWebSafeFileName"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\FileSystem\u003A\u003AwriteFile\u0028\u0029",
            "name": "writeFile",
            "summary": "Write\u0020file.\u0020\u0028Create\u0020a\u0020file\u0029.",
            "url": "classes/Rdb-System-Libraries-FileSystem.html#method_writeFile"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\FileSystem\u003A\u003A\u0024trackCopy",
            "name": "trackCopy",
            "summary": "",
            "url": "classes/Rdb-System-Libraries-FileSystem.html#property_trackCopy"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\FileSystem\u003A\u003A\u0024trackCreate",
            "name": "trackCreate",
            "summary": "",
            "url": "classes/Rdb-System-Libraries-FileSystem.html#property_trackCreate"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\FileSystem\u003A\u003A\u0024trackDeleted",
            "name": "trackDeleted",
            "summary": "",
            "url": "classes/Rdb-System-Libraries-FileSystem.html#property_trackDeleted"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\FileSystem\u003A\u003A\u0024root",
            "name": "root",
            "summary": "",
            "url": "classes/Rdb-System-Libraries-FileSystem.html#property_root"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Form",
            "name": "Form",
            "summary": "Form\u0020class.",
            "url": "classes/Rdb-System-Libraries-Form.html"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Form\u003A\u003A__callStatic\u0028\u0029",
            "name": "__callStatic",
            "summary": "Call\u0020static\u0020magic\u0020method.",
            "url": "classes/Rdb-System-Libraries-Form.html#method___callStatic"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Form\u003A\u003AisMatched\u0028\u0029",
            "name": "isMatched",
            "summary": "Check\u0020if\u0020the\u0020value\u0020and\u0020input\u0020value\u0020is\u0020matched.",
            "url": "classes/Rdb-System-Libraries-Form.html#method_isMatched"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Form\u003A\u003AsetChecked\u0028\u0029",
            "name": "setChecked",
            "summary": "Set\u0020checked\u0020if\u0020value\u0020and\u0020input\u0020value\u0020is\u0020matched.",
            "url": "classes/Rdb-System-Libraries-Form.html#method_setChecked"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Form\u003A\u003AsetSelected\u0028\u0029",
            "name": "setSelected",
            "summary": "Set\u0020selected\u0020if\u0020value\u0020and\u0020input\u0020value\u0020is\u0020matched.",
            "url": "classes/Rdb-System-Libraries-Form.html#method_setSelected"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Input",
            "name": "Input",
            "summary": "Input\u0020class.",
            "url": "classes/Rdb-System-Libraries-Input.html"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Input\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Class\u0020constructor.",
            "url": "classes/Rdb-System-Libraries-Input.html#method___construct"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Input\u003A\u003A__get\u0028\u0029",
            "name": "__get",
            "summary": "Magic\u0020get.",
            "url": "classes/Rdb-System-Libraries-Input.html#method___get"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Input\u003A\u003AdetermineAcceptContentType\u0028\u0029",
            "name": "determineAcceptContentType",
            "summary": "Determine\u0020HTTP\u0020accept\u0020content\u002Dtype.",
            "url": "classes/Rdb-System-Libraries-Input.html#method_determineAcceptContentType"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Input\u003A\u003A\u0024Container",
            "name": "Container",
            "summary": "",
            "url": "classes/Rdb-System-Libraries-Input.html#property_Container"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Input\u003A\u003A\u0024httpAcceptContentTypes",
            "name": "httpAcceptContentTypes",
            "summary": "",
            "url": "classes/Rdb-System-Libraries-Input.html#property_httpAcceptContentTypes"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Logger",
            "name": "Logger",
            "summary": "Log\u0020class\u0020that\u0020is\u0020working\u0020on\u0020monolog.",
            "url": "classes/Rdb-System-Libraries-Logger.html"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Logger\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Logger\u0020class\u0020constructor.",
            "url": "classes/Rdb-System-Libraries-Logger.html#method___construct"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Logger\u003A\u003AgetLogger\u0028\u0029",
            "name": "getLogger",
            "summary": "Get\u0020Logger\u0020class\u0020with\u0020specified\u0020channel.",
            "url": "classes/Rdb-System-Libraries-Logger.html#method_getLogger"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Logger\u003A\u003AsetLogLevelNameAndNumber\u0028\u0029",
            "name": "setLogLevelNameAndNumber",
            "summary": "Set\u0020log\u0020level\u0020name\u0020\u0028readable\u0020such\u0020as\u0020debug,\u0020info,\u0020etc...\u0029\u0020and\u0020number\u0020from\u0020\u0060\\Monolog\\Logger\u003A\u003ACONSTANT\u0060.",
            "url": "classes/Rdb-System-Libraries-Logger.html#method_setLogLevelNameAndNumber"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Logger\u003A\u003Awrite\u0028\u0029",
            "name": "write",
            "summary": "Write\u0020the\u0020message\u0020to\u0020log\u0020file.",
            "url": "classes/Rdb-System-Libraries-Logger.html#method_write"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Logger\u003A\u003A\u0024Config",
            "name": "Config",
            "summary": "",
            "url": "classes/Rdb-System-Libraries-Logger.html#property_Config"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Logger\u003A\u003A\u0024Container",
            "name": "Container",
            "summary": "",
            "url": "classes/Rdb-System-Libraries-Logger.html#property_Container"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Logger\u003A\u003A\u0024donotLogLevel",
            "name": "donotLogLevel",
            "summary": "",
            "url": "classes/Rdb-System-Libraries-Logger.html#property_donotLogLevel"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Logger\u003A\u003A\u0024logEnabled",
            "name": "logEnabled",
            "summary": "",
            "url": "classes/Rdb-System-Libraries-Logger.html#property_logEnabled"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Logger\u003A\u003A\u0024logLevel",
            "name": "logLevel",
            "summary": "",
            "url": "classes/Rdb-System-Libraries-Logger.html#property_logLevel"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Logger\u003A\u003A\u0024logLevelName",
            "name": "logLevelName",
            "summary": "",
            "url": "classes/Rdb-System-Libraries-Logger.html#property_logLevelName"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Profiler",
            "name": "Profiler",
            "summary": "Profiler\u0020class\u0020that\u0020extends\u0020Rundiz\\Profiler\\Profiler.",
            "url": "classes/Rdb-System-Libraries-Profiler.html"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Profiler\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Profiler\u0020class\u0020constructor.",
            "url": "classes/Rdb-System-Libraries-Profiler.html#method___construct"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Url",
            "name": "Url",
            "summary": "URL\u0020class.",
            "url": "classes/Rdb-System-Libraries-Url.html"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Url\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Class\u0020constructor.",
            "url": "classes/Rdb-System-Libraries-Url.html#method___construct"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Url\u003A\u003AbuildUrl\u0028\u0029",
            "name": "buildUrl",
            "summary": "Build\u0020URL\u0020from\u0020\u0060parse_url\u0028\u0029\u0060\u0020function.",
            "url": "classes/Rdb-System-Libraries-Url.html#method_buildUrl"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Url\u003A\u003AgetAppBasedPath\u0028\u0029",
            "name": "getAppBasedPath",
            "summary": "Get\u0020application\u0020based\u0020path\u0020without\u0020trailing\u0020slash.",
            "url": "classes/Rdb-System-Libraries-Url.html#method_getAppBasedPath"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Url\u003A\u003AgetCurrentUrl\u0028\u0029",
            "name": "getCurrentUrl",
            "summary": "Get\u0020current\u0020URL.",
            "url": "classes/Rdb-System-Libraries-Url.html#method_getCurrentUrl"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Url\u003A\u003AgetDomainProtocol\u0028\u0029",
            "name": "getDomainProtocol",
            "summary": "Get\u0020domain\u0020with\u0020protocol.\u0020Example\u003A\u0020https\u003A\/\/mydomain.com",
            "url": "classes/Rdb-System-Libraries-Url.html#method_getDomainProtocol"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Url\u003A\u003AgetPath\u0028\u0029",
            "name": "getPath",
            "summary": "Get\u0020path\u0020of\u0020current\u0020URL\u0020but\u0020related\u0020from\u0020public\u0020URL\u0020without\u0020any\u0020query\u0020string\u0020and\u0020no\u0020trailing\u0020slash.",
            "url": "classes/Rdb-System-Libraries-Url.html#method_getPath"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Url\u003A\u003AgetPublicUrl\u0028\u0029",
            "name": "getPublicUrl",
            "summary": "Get\u0020public\u0020URL.",
            "url": "classes/Rdb-System-Libraries-Url.html#method_getPublicUrl"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Url\u003A\u003AgetPublicModuleUrl\u0028\u0029",
            "name": "getPublicModuleUrl",
            "summary": "Get\u0020public\/Modules\u0020URL\u0020from\u0020specific\u0020module\u0020path.",
            "url": "classes/Rdb-System-Libraries-Url.html#method_getPublicModuleUrl"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Url\u003A\u003AgetQuerystring\u0028\u0029",
            "name": "getQuerystring",
            "summary": "Get\u0020current\u0020query\u0020string\u0020\u0028\u003Fparam\u003Dvalue\u0029\u0020with\u0020question\u0020mark\u0020sign\u0020\u0028\u003F\u0029\u0020if\u0020it\u0020is\u0020not\u0020empty.",
            "url": "classes/Rdb-System-Libraries-Url.html#method_getQuerystring"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Url\u003A\u003AgetSegment\u0028\u0029",
            "name": "getSegment",
            "summary": "Get\u0020the\u0020specific\u0020URL\u0020segment.",
            "url": "classes/Rdb-System-Libraries-Url.html#method_getSegment"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Url\u003A\u003AgetSegments\u0028\u0029",
            "name": "getSegments",
            "summary": "Get\u0020URL\u0020segments.",
            "url": "classes/Rdb-System-Libraries-Url.html#method_getSegments"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Url\u003A\u003ArawUrlEncodeAllParts\u0028\u0029",
            "name": "rawUrlEncodeAllParts",
            "summary": "Encode\u0020all\u0020parts\u0020of\u0020the\u0020URL.",
            "url": "classes/Rdb-System-Libraries-Url.html#method_rawUrlEncodeAllParts"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Url\u003A\u003ArawUrlEncodeFragment\u0028\u0029",
            "name": "rawUrlEncodeFragment",
            "summary": "Encode\u0020the\u0020fragment\u0020\u0028\u0023anchor\u0029\u0020on\u0020the\u0020URL\u0020use\u0020\u0060rawurlencode\u0028\u0029\u0060.",
            "url": "classes/Rdb-System-Libraries-Url.html#method_rawUrlEncodeFragment"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Url\u003A\u003ArawUrlEncodeQuerystring\u0028\u0029",
            "name": "rawUrlEncodeQuerystring",
            "summary": "Use\u0020\u0060RFC\u00203986\u0060\u0020to\u0020encode\u0020the\u0020query\u0020string\u0020\u0028same\u0020as\u0020\u0060rawurlencode\u0060\u0020function\u0029.",
            "url": "classes/Rdb-System-Libraries-Url.html#method_rawUrlEncodeQuerystring"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Url\u003A\u003ArawUrlEncodeSegments\u0028\u0029",
            "name": "rawUrlEncodeSegments",
            "summary": "Use\u0020\u0060rawurlencode\u0028\u0029\u0060\u0020to\u0020encode\u0020multiple\u0020segments.",
            "url": "classes/Rdb-System-Libraries-Url.html#method_rawUrlEncodeSegments"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Url\u003A\u003ArawUrlEncodeUsernamePassword\u0028\u0029",
            "name": "rawUrlEncodeUsernamePassword",
            "summary": "Encode\u0020the\u0020username\u0020and\u0020password\u0020on\u0020the\u0020URL\u0020use\u0020\u0060rawurlencode\u0028\u0029\u0060.",
            "url": "classes/Rdb-System-Libraries-Url.html#method_rawUrlEncodeUsernamePassword"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Url\u003A\u003AremoveQuerystring\u0028\u0029",
            "name": "removeQuerystring",
            "summary": "Remove\u0020query\u0020string.",
            "url": "classes/Rdb-System-Libraries-Url.html#method_removeQuerystring"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Url\u003A\u003AremoveUnsafeUrlCharacters\u0028\u0029",
            "name": "removeUnsafeUrlCharacters",
            "summary": "Remove\u0020unsafe\u0020URL\u0020characters\u0020but\u0020not\u0020URL\u0020encode.",
            "url": "classes/Rdb-System-Libraries-Url.html#method_removeUnsafeUrlCharacters"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Url\u003A\u003A\u0024Container",
            "name": "Container",
            "summary": "",
            "url": "classes/Rdb-System-Libraries-Url.html#property_Container"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Xml",
            "name": "Xml",
            "summary": "XML\u0020class.",
            "url": "classes/Rdb-System-Libraries-Xml.html"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Xml\u003A\u003AfromArray\u0028\u0029",
            "name": "fromArray",
            "summary": "Convert\u0020array\u0020to\u0020XML.",
            "url": "classes/Rdb-System-Libraries-Xml.html#method_fromArray"
        },                {
            "fqsen": "\\Rdb\\System\\Middleware\\ErrorHandler",
            "name": "ErrorHandler",
            "summary": "Error\u0020handler\u0020for\u0020the\u0020framework.",
            "url": "classes/Rdb-System-Middleware-ErrorHandler.html"
        },                {
            "fqsen": "\\Rdb\\System\\Middleware\\ErrorHandler\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "The\u0020class\u0020constructor.",
            "url": "classes/Rdb-System-Middleware-ErrorHandler.html#method___construct"
        },                {
            "fqsen": "\\Rdb\\System\\Middleware\\ErrorHandler\u003A\u003AchangeLogErrorsIniSetting\u0028\u0029",
            "name": "changeLogErrorsIniSetting",
            "summary": "Change\u0020\u0060log_errors\u0060\u0020in\u0020the\u0020php.ini\u0020depend\u0020on\u0020\u0060log.donotLogLevel\u0060\u0020in\u0020config\/\u005Benvironment\u005D\/app.php\u0020file.",
            "url": "classes/Rdb-System-Middleware-ErrorHandler.html#method_changeLogErrorsIniSetting"
        },                {
            "fqsen": "\\Rdb\\System\\Middleware\\ErrorHandler\u003A\u003Ainit\u0028\u0029",
            "name": "init",
            "summary": "Initialize\u0020the\u0020error\u0020handler.",
            "url": "classes/Rdb-System-Middleware-ErrorHandler.html#method_init"
        },                {
            "fqsen": "\\Rdb\\System\\Middleware\\ErrorHandler\u003A\u003A\u0024Config",
            "name": "Config",
            "summary": "",
            "url": "classes/Rdb-System-Middleware-ErrorHandler.html#property_Config"
        },                {
            "fqsen": "\\Rdb\\System\\Middleware\\ErrorHandler\u003A\u003A\u0024Container",
            "name": "Container",
            "summary": "",
            "url": "classes/Rdb-System-Middleware-ErrorHandler.html#property_Container"
        },                {
            "fqsen": "\\Rdb\\System\\Middleware\\ErrorHandler\u003A\u003A\u0024donotLogLevel",
            "name": "donotLogLevel",
            "summary": "",
            "url": "classes/Rdb-System-Middleware-ErrorHandler.html#property_donotLogLevel"
        },                {
            "fqsen": "\\Rdb\\System\\Middleware\\I18n",
            "name": "I18n",
            "summary": "I18n\u0020or\u0020internationalisation\u0020for\u0020the\u0020framework.",
            "url": "classes/Rdb-System-Middleware-I18n.html"
        },                {
            "fqsen": "\\Rdb\\System\\Middleware\\I18n\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "The\u0020class\u0020constructor.",
            "url": "classes/Rdb-System-Middleware-I18n.html#method___construct"
        },                {
            "fqsen": "\\Rdb\\System\\Middleware\\I18n\u003A\u003AgetLocale\u0028\u0029",
            "name": "getLocale",
            "summary": "Get\u0020locale\u0020to\u0020set\u0020in\u0020PHP.",
            "url": "classes/Rdb-System-Middleware-I18n.html#method_getLocale"
        },                {
            "fqsen": "\\Rdb\\System\\Middleware\\I18n\u003A\u003Ainit\u0028\u0029",
            "name": "init",
            "summary": "Initialize\u0020the\u0020language\/locale.",
            "url": "classes/Rdb-System-Middleware-I18n.html#method_init"
        },                {
            "fqsen": "\\Rdb\\System\\Middleware\\I18n\u003A\u003Aredirect\u0028\u0029",
            "name": "redirect",
            "summary": "Redirect\u0020and\u0020then\u0020exit.",
            "url": "classes/Rdb-System-Middleware-I18n.html#method_redirect"
        },                {
            "fqsen": "\\Rdb\\System\\Middleware\\I18n\u003A\u003A\u0024Config",
            "name": "Config",
            "summary": "",
            "url": "classes/Rdb-System-Middleware-I18n.html#property_Config"
        },                {
            "fqsen": "\\Rdb\\System\\Middleware\\I18n\u003A\u003A\u0024Container",
            "name": "Container",
            "summary": "",
            "url": "classes/Rdb-System-Middleware-I18n.html#property_Container"
        },                {
            "fqsen": "\\Rdb\\System\\Middleware\\Profiler",
            "name": "Profiler",
            "summary": "Profiler\u0020or\u0020benchmark\u0020the\u0020application.",
            "url": "classes/Rdb-System-Middleware-Profiler.html"
        },                {
            "fqsen": "\\Rdb\\System\\Middleware\\Profiler\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "The\u0020class\u0020constructor.",
            "url": "classes/Rdb-System-Middleware-Profiler.html#method___construct"
        },                {
            "fqsen": "\\Rdb\\System\\Middleware\\Profiler\u003A\u003AappendProfiler\u0028\u0029",
            "name": "appendProfiler",
            "summary": "Append\u0020profiler\u0020to\u0020html\u0020body.",
            "url": "classes/Rdb-System-Middleware-Profiler.html#method_appendProfiler"
        },                {
            "fqsen": "\\Rdb\\System\\Middleware\\Profiler\u003A\u003AcheckDisplayProfiler\u0028\u0029",
            "name": "checkDisplayProfiler",
            "summary": "Check\u0020that\u0020does\u0020it\u0020should\u0020be\u0020display\u0020the\u0020profiler.",
            "url": "classes/Rdb-System-Middleware-Profiler.html#method_checkDisplayProfiler"
        },                {
            "fqsen": "\\Rdb\\System\\Middleware\\Profiler\u003A\u003AdisplayDb\u0028\u0029",
            "name": "displayDb",
            "summary": "Display\u0020Profiler\u0020DB.",
            "url": "classes/Rdb-System-Middleware-Profiler.html#method_displayDb"
        },                {
            "fqsen": "\\Rdb\\System\\Middleware\\Profiler\u003A\u003Aend\u0028\u0029",
            "name": "end",
            "summary": "End\u0020profiler.",
            "url": "classes/Rdb-System-Middleware-Profiler.html#method_end"
        },                {
            "fqsen": "\\Rdb\\System\\Middleware\\Profiler\u003A\u003Ainit\u0028\u0029",
            "name": "init",
            "summary": "Initialize\u0020the\u0020profiler.",
            "url": "classes/Rdb-System-Middleware-Profiler.html#method_init"
        },                {
            "fqsen": "\\Rdb\\System\\Middleware\\Profiler\u003A\u003A\u0024Config",
            "name": "Config",
            "summary": "",
            "url": "classes/Rdb-System-Middleware-Profiler.html#property_Config"
        },                {
            "fqsen": "\\Rdb\\System\\Middleware\\Profiler\u003A\u003A\u0024Container",
            "name": "Container",
            "summary": "",
            "url": "classes/Rdb-System-Middleware-Profiler.html#property_Container"
        },                {
            "fqsen": "\\Rdb\\System\\Middleware\\RemoveTrailingSlash",
            "name": "RemoveTrailingSlash",
            "summary": "Remove\u0020trailing\u0020slash\u0020from\u0020the\u0020URL\u0020by\u0020redirect\u0020it.",
            "url": "classes/Rdb-System-Middleware-RemoveTrailingSlash.html"
        },                {
            "fqsen": "\\Rdb\\System\\Middleware\\RemoveTrailingSlash\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "The\u0020class\u0020constructor.",
            "url": "classes/Rdb-System-Middleware-RemoveTrailingSlash.html#method___construct"
        },                {
            "fqsen": "\\Rdb\\System\\Middleware\\RemoveTrailingSlash\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Run\u0020the\u0020middleware.",
            "url": "classes/Rdb-System-Middleware-RemoveTrailingSlash.html#method_run"
        },                {
            "fqsen": "\\Rdb\\System\\Middleware\\RemoveTrailingSlash\u003A\u003A\u0024Container",
            "name": "Container",
            "summary": "",
            "url": "classes/Rdb-System-Middleware-RemoveTrailingSlash.html#property_Container"
        },                {
            "fqsen": "\\Rdb\\System\\Modules",
            "name": "Modules",
            "summary": "Modules\u0020class.",
            "url": "classes/Rdb-System-Modules.html"
        },                {
            "fqsen": "\\Rdb\\System\\Modules\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Modules\u0020class\u0020constructor.",
            "url": "classes/Rdb-System-Modules.html#method___construct"
        },                {
            "fqsen": "\\Rdb\\System\\Modules\u003A\u003AcopyComposer\u0028\u0029",
            "name": "copyComposer",
            "summary": "Copy\u0020moduleComposer.json\u0020to\u0020main\u0020application\u0020composer.json.",
            "url": "classes/Rdb-System-Modules.html#method_copyComposer"
        },                {
            "fqsen": "\\Rdb\\System\\Modules\u003A\u003AcopyComposerPackageIfNewer\u0028\u0029",
            "name": "copyComposerPackageIfNewer",
            "summary": "Copy\u0020composer\u0020package\u0020from\u0020module\u0020to\u0020root\u0020if\u0020module\u0020is\u0020using\u0020newer\u0020version\u0020range.",
            "url": "classes/Rdb-System-Modules.html#method_copyComposerPackageIfNewer"
        },                {
            "fqsen": "\\Rdb\\System\\Modules\u003A\u003AcopyComposerAllModules\u0028\u0029",
            "name": "copyComposerAllModules",
            "summary": "Copy\u0020moduleComposer.json\u0020from\u0020all\u0020modules\u0020into\u0020main\u0020app\u0027s\u0020composer.json",
            "url": "classes/Rdb-System-Modules.html#method_copyComposerAllModules"
        },                {
            "fqsen": "\\Rdb\\System\\Modules\u003A\u003Aenable\u0028\u0029",
            "name": "enable",
            "summary": "Set\u0020module\u0020to\u0020be\u0020disabled\u0020or\u0020enabled\u0020depend\u0020on\u0020\u0060\u0024enable\u0060\u0020argument.",
            "url": "classes/Rdb-System-Modules.html#method_enable"
        },                {
            "fqsen": "\\Rdb\\System\\Modules\u003A\u003Aexecute\u0028\u0029",
            "name": "execute",
            "summary": "Execute\u0020a\u0020module\u0020controller\/method.",
            "url": "classes/Rdb-System-Modules.html#method_execute"
        },                {
            "fqsen": "\\Rdb\\System\\Modules\u003A\u003Aexists\u0028\u0029",
            "name": "exists",
            "summary": "Check\u0020if\u0020module\u0020exists.",
            "url": "classes/Rdb-System-Modules.html#method_exists"
        },                {
            "fqsen": "\\Rdb\\System\\Modules\u003A\u003AgetComposerDefault\u0028\u0029",
            "name": "getComposerDefault",
            "summary": "Get\u0020default\u0020composer\u0020json\u0020file.",
            "url": "classes/Rdb-System-Modules.html#method_getComposerDefault"
        },                {
            "fqsen": "\\Rdb\\System\\Modules\u003A\u003AgetCurrentModule\u0028\u0029",
            "name": "getCurrentModule",
            "summary": "Get\u0020current\u0020module.",
            "url": "classes/Rdb-System-Modules.html#method_getCurrentModule"
        },                {
            "fqsen": "\\Rdb\\System\\Modules\u003A\u003AgetModules\u0028\u0029",
            "name": "getModules",
            "summary": "Get\u0020list\u0020of\u0020modules.",
            "url": "classes/Rdb-System-Modules.html#method_getModules"
        },                {
            "fqsen": "\\Rdb\\System\\Modules\u003A\u003AgetModuleSystemName\u0028\u0029",
            "name": "getModuleSystemName",
            "summary": "Get\u0020module\u0020system\u0020name\u0020\u0028module\u0020folder\u0020name\u0029\u0020from\u0020full\u0020path\u0020to\u0020such\u0020as\u0020module\u0020folder\u0020or\u0020any\u0020file\u0020in\u0020that\u0020module.",
            "url": "classes/Rdb-System-Modules.html#method_getModuleSystemName"
        },                {
            "fqsen": "\\Rdb\\System\\Modules\u003A\u003AregisterAutoload\u0028\u0029",
            "name": "registerAutoload",
            "summary": "Register\u0020auto\u0020load\u0020for\u0020modules\u0020that\u0020is\u0020not\u0020disabled.",
            "url": "classes/Rdb-System-Modules.html#method_registerAutoload"
        },                {
            "fqsen": "\\Rdb\\System\\Modules\u003A\u003AsetCurrentModule\u0028\u0029",
            "name": "setCurrentModule",
            "summary": "Set\u0020current\u0020module\u0020from\u0020specific\u0020controller.",
            "url": "classes/Rdb-System-Modules.html#method_setCurrentModule"
        },                {
            "fqsen": "\\Rdb\\System\\Modules\u003A\u003A\u0024Container",
            "name": "Container",
            "summary": "",
            "url": "classes/Rdb-System-Modules.html#property_Container"
        },                {
            "fqsen": "\\Rdb\\System\\Modules\u003A\u003A\u0024currentModule",
            "name": "currentModule",
            "summary": "",
            "url": "classes/Rdb-System-Modules.html#property_currentModule"
        },                {
            "fqsen": "\\Rdb\\System\\Modules\u003A\u003A\u0024modules",
            "name": "modules",
            "summary": "",
            "url": "classes/Rdb-System-Modules.html#property_modules"
        },                {
            "fqsen": "\\Rdb\\System\\Router",
            "name": "Router",
            "summary": "Router\u0020class.",
            "url": "classes/Rdb-System-Router.html"
        },                {
            "fqsen": "\\Rdb\\System\\Router\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Router\u0020class.",
            "url": "classes/Rdb-System-Router.html#method___construct"
        },                {
            "fqsen": "\\Rdb\\System\\Router\u003A\u003Adispatch\u0028\u0029",
            "name": "dispatch",
            "summary": "Setup\u0020and\u0020then\u0020dispatch\u0020the\u0020route.",
            "url": "classes/Rdb-System-Router.html#method_dispatch"
        },                {
            "fqsen": "\\Rdb\\System\\Router\u003A\u003AfilterMethod\u0028\u0029",
            "name": "filterMethod",
            "summary": "Filter\u0020method\u0020to\u0020replace\u0020\u0060any\u0060\u0020method\u0020to\u0020all\u0020available\u0020methods\u0020and\u0020upper\u0020case\u0020for\u0020method\u0020array.",
            "url": "classes/Rdb-System-Router.html#method_filterMethod"
        },                {
            "fqsen": "\\Rdb\\System\\Router\u003A\u003AgetControllerMethodName\u0028\u0029",
            "name": "getControllerMethodName",
            "summary": "Get\u0020full\u0020controller\u0020class\u0020name\u0020and\u0020full\u0020method\u0020name\u0020from\u0020string\u0020or\u0020handler.",
            "url": "classes/Rdb-System-Router.html#method_getControllerMethodName"
        },                {
            "fqsen": "\\Rdb\\System\\Router\u003A\u003AsetupRoute\u0028\u0029",
            "name": "setupRoute",
            "summary": "Setup\u0020the\u0020routes\u0020and\u0020create\u0020dispatcher.",
            "url": "classes/Rdb-System-Router.html#method_setupRoute"
        },                {
            "fqsen": "\\Rdb\\System\\Router\u003A\u003A\u0024Container",
            "name": "Container",
            "summary": "",
            "url": "classes/Rdb-System-Router.html#property_Container"
        },                {
            "fqsen": "\\Rdb\\System\\Views",
            "name": "Views",
            "summary": "Views\u0020class.",
            "url": "classes/Rdb-System-Views.html"
        },                {
            "fqsen": "\\Rdb\\System\\Views\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Load\u0020the\u0020views\u0020file.",
            "url": "classes/Rdb-System-Views.html#method___construct"
        },                {
            "fqsen": "\\Rdb\\System\\Views\u003A\u003AlocateViews\u0028\u0029",
            "name": "locateViews",
            "summary": "Locate\u0020views\u0020file.",
            "url": "classes/Rdb-System-Views.html#method_locateViews"
        },                {
            "fqsen": "\\Rdb\\System\\Views\u003A\u003Arender\u0028\u0029",
            "name": "render",
            "summary": "Render\u0020the\u0020views\u0020file.",
            "url": "classes/Rdb-System-Views.html#method_render"
        },                {
            "fqsen": "\\Rdb\\System\\Views\u003A\u003A\u0024Container",
            "name": "Container",
            "summary": "",
            "url": "classes/Rdb-System-Views.html#property_Container"
        },                {
            "fqsen": "\\Rdb\\System\\Views\u003A\u003A\u0024controllerMethod",
            "name": "controllerMethod",
            "summary": "",
            "url": "classes/Rdb-System-Views.html#property_controllerMethod"
        },                {
            "fqsen": "\\Rdb\\System\\Views\u003A\u003A\u0024Modules",
            "name": "Modules",
            "summary": "",
            "url": "classes/Rdb-System-Views.html#property_Modules"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Rdb\\System",
            "name": "System",
            "summary": "",
            "url": "namespaces/rdb-system.html"
        },                {
            "fqsen": "\\Rdb",
            "name": "Rdb",
            "summary": "",
            "url": "namespaces/rdb.html"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Console",
            "name": "Console",
            "summary": "",
            "url": "namespaces/rdb-system-core-console.html"
        },                {
            "fqsen": "\\Rdb\\System\\Core",
            "name": "Core",
            "summary": "",
            "url": "namespaces/rdb-system-core.html"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Console\\Phinx",
            "name": "Phinx",
            "summary": "",
            "url": "namespaces/rdb-system-core-console-phinx.html"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Controllers",
            "name": "Controllers",
            "summary": "",
            "url": "namespaces/rdb-system-core-controllers.html"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Controllers\\Error",
            "name": "Error",
            "summary": "",
            "url": "namespaces/rdb-system-core-controllers-error.html"
        },                {
            "fqsen": "\\Rdb\\System\\Core\\Models",
            "name": "Models",
            "summary": "",
            "url": "namespaces/rdb-system-core-models.html"
        },                {
            "fqsen": "\\Rdb\\System\\Interfaces",
            "name": "Interfaces",
            "summary": "",
            "url": "namespaces/rdb-system-interfaces.html"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries",
            "name": "Libraries",
            "summary": "",
            "url": "namespaces/rdb-system-libraries.html"
        },                {
            "fqsen": "\\Rdb\\System\\Libraries\\Db",
            "name": "Db",
            "summary": "",
            "url": "namespaces/rdb-system-libraries-db.html"
        },                {
            "fqsen": "\\Rdb\\System\\Middleware",
            "name": "Middleware",
            "summary": "",
            "url": "namespaces/rdb-system-middleware.html"
        }            ]
);
